USE ROLE ACCOUNTADMIN;

CREATE USER TF_SERVICEUSER
    TYPE = SERVICE
    COMMENT = "Service user for Terraforming Snowflake"
    RSA_PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-----END PUBLIC KEY-----";

GRANT ROLE SYSADMIN TO USER TF_SERVICEUSER;
GRANT ROLE SECURITYADMIN TO USER TF_SERVICEUSER;

USE ROLE ACCOUNTADMIN;
SHOW GRANTS TO USER TF_SERVICEUSER;