USE ROLE ACCOUNTADMIN;

CREATE USER TF_SERVICEUSER
    TYPE = SERVICE
    COMMENT = "Service user for Terraforming Snowflake"
    RSA_PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----
  ## put your rsa key here
-----END PUBLIC KEY-----";

GRANT ROLE SYSADMIN TO USER TF_SERVICEUSER;
GRANT ROLE SECURITYADMIN TO USER TF_SERVICEUSER;
